language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable  #设置相应的版本

install:
  - npm install -D  #安装builder依赖
  - cd ./test/template-project
  - npm install -D #安装模板项目依赖

script:
  - npm test


after_failed:
  - curl -X POST -H 'Content-type: application/json' --data '{"msgtype":"markdown","markdown":{"content":"builder-webpack4测试失败，[查看状态](https://travis-ci.org/feflow/builder-webpack4)"}}' https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=161b28c8-c676-42ff-b8a5-f57d4fca551b

after_success:
  - curl -X POST -H 'Content-type: application/json' --data '{"msgtype":"markdown","markdown":{"content":"builder-webpack4测试成功，[查看状态](https://travis-ci.org/feflow/builder-webpack4)"}}' https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=161b28c8-c676-42ff-b8a5-f57d4fca551b